// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3tzp5E8MKAQFRFQZJ12E0U9UL-V_0xAo',
    appId: '1:905688673719:web:1d0c95f1f05019dcc54c32',
    messagingSenderId: '905688673719',
    projectId: 'flutterisa',
    authDomain: 'flutterisa.firebaseapp.com',
    storageBucket: 'flutterisa.appspot.com',
    measurementId: 'G-14H71NL3G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw8iZkGNE5DwRMDLhJz03Gzb7hypj_7_U',
    appId: '1:905688673719:android:5ad7e002d965f5d8c54c32',
    messagingSenderId: '905688673719',
    projectId: 'flutterisa',
    storageBucket: 'flutterisa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABS5huK_tFCiwCwel2YWi577X4Wsa755E',
    appId: '1:905688673719:ios:af7e415f6fc437d2c54c32',
    messagingSenderId: '905688673719',
    projectId: 'flutterisa',
    storageBucket: 'flutterisa.appspot.com',
    iosClientId: '905688673719-kq6s1jtmpccc3auq9luqsvphlv7ttjtt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABS5huK_tFCiwCwel2YWi577X4Wsa755E',
    appId: '1:905688673719:ios:0edd1df26f34a9dfc54c32',
    messagingSenderId: '905688673719',
    projectId: 'flutterisa',
    storageBucket: 'flutterisa.appspot.com',
    iosClientId: '905688673719-7r91jnq3a65qqvst9h3dgfh6mdaruje4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
